### PR TITLE
Fix dune runtest

### PR DESCRIPTION
**Pull request by thizanne**
cc @Leonidas-from-XIV 

This is hoped to fix the CI failures

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
Yes, this seems to help the tests. Unfortunately it is still failing on 4.02.3. Could you try removing the `OCAML_SWITCH` part from `.travis.yml`, maybe that will solve it?

**Review by Leonidas-from-XIV — APPROVED** [review]
It is definitely a step in the right direction, hope we can get 4.02 to work as well.

**Comment by thizanne** [comment]
One test depends on core_bench>=0.11, which itself depends on ocaml >= 4.04, hence the failure. I'll check if we can run the tests on 4.04 (debian stable has 4.05, so that even doesn't seem too strict as a requirement), and merge as-is otherwise (and we shall see later).

**Comment by Leonidas-from-XIV** [comment]
Running it on 4.04 is easy, just requires one additional line in the `.travis.yml`. `ocaml-ci-scripts` covers a wide range of compilers.

The tests are however running on 4.10 which I would think is good enough, I don't really expect changes in the compiler break the code. Having the minimum and maximum supported version of the compiler is useful to see if things build correctly (e.g. fail by accidentally using features that the oldest compiler does not support yet), the testsuite I would say is of lesser importance as long as it is run and successfully finishes on some version.

**Comment by thizanne** [comment]
Fine with me.

**Pull request merged**
