### PR TITLE
refactor: simplify bit shuffling

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Comment by rgrinberg** [comment]
ping @thizanne

**Comment by thizanne** [comment]
Sorry, I have been quite busy this week. I will look at it in the next few days.

**Comment by thizanne** [comment]
In the meantime could you for instance rebase and push again so that we can try the new shiny GH actions?

**Comment by rgrinberg** [comment]
Looks like there's an issue on windows.

**Comment by thizanne** [comment]
There is indeed, but it's a known current issue with ocaml/setup-ocaml, we can ignore that.

Regarding your change, I have mixed feelings. Overall, I'm wary of unsafe accesses, even if that seems indeed correct here, since it can hide bugs and I don't believe the library is mature and battle-tested enough to guarantee that it's bug free and will remain it this way (especially since we consider non-trivial developments). I also believe that I already tried that when first developing it, and eventually abandoned it because it had no observable performance impact.

So unless you do have a benchmark that demonstrates that we gain observable performances, in which case that would make a strong argument for the change, I'd be leaning on the side of keeping safe accesses for now.

**Comment by rgrinberg** [comment]
There are some gains, but they aren't very impressive. In any case, I removed them.

Instead, I updated the PR to simplify the bit shuffling. The result is a little faster and also easier to read.

**Review by thizanne — APPROVED** [review]
Seems reasonable and correct, thanks!

**Pull request merged**
