### PR TITLE
ci: update travis to OCaml 4.12

### PR DESCRIPTION
**Pull request by thizanne**
4.10 -> 4.13

### CODE REVIEW

**Review by Leonidas-from-XIV — APPROVED** [review]
Makes a lot of sense.

With the demise of Travis we should consider migrating to somewhere else like the [OCaml CI](https://github.com/ocurrent/ocaml-ci).

**Comment by thizanne** [comment]
I'm fine with a migration, but since we really don't have a lot of traffic & travis still works I don't have enough time×motivation to set it up myself right now.

**Comment by thizanne** [comment]
Seems like I spoke too fast and the travis script doesn't support 4.13 anymore. I'll still move to 4.12 and look up the new shiny systems.

**Comment by Leonidas-from-XIV** [comment]
I can make a PR to ocaml-ci-scripts because the newest "final" release that is supported at the moment is 4.11 (4.12 is a preview version).

**Comment by thizanne** [comment]
Indeed, 4.12 doesn't work because 4.12.0+trunk doesn't exist anymore. Upgrading to 4.11 makes little sense, let's just drop this and move to something more modern.

**Comment by Leonidas-from-XIV** [comment]
PR created: https://github.com/ocaml/ocaml-ci-scripts/pull/354

**Pull request closed without merging**
